"""describe your change

Revision ID: 45b36144f165
Revises: 98e01a31e442
Create Date: 2025-09-24 23:53:13.915219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45b36144f165'
down_revision = '98e01a31e442'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
